defaults:
  - _self_
  - ../skeleton@skeleton: rat7m

_target_: csbev.dataset.base.Rat7MDataset

name: rat7m
dataset_type: dannce_mat
datapaths:
dataroot: /media/mynewdrive/datasets/rat7m/annotations
data_rep: xyz
alignment: lock_facing
normalize: false
scale: 0.01
seqlen: 128
t_downsample: 3

split:
  method: subject
  split_ids_train: ['mocap-s1-d1']
  split_ids_val:
    - mocap-s1-d1
    - mocap-s2-d1
    - mocap-s3-d1
    - mocap-s4-d1
    - mocap-s5-d1
    - mocap-s5-d2

  # split_ids:
  #   - mocap-s1-d1
  #   - mocap-s2-d1
  #   - mocap-s3-d1
  #   - mocap-s4-d1
  #   - mocap-s5-d1
  #   - mocap-s5-d2