defaults:
  - _self_
  # - dataset@datasets.rat23_2d: rat23_2d
  # - dataset@datasets.mouse_demo_2d: mouse_demo_2d
  # - dataset@datasets.calms21: calms21
  # - dataset@datasets.mouse_moseq_2d: mouse_moseq_2d

  - dataset@datasets.rat23: rat23
  # - dataset@datasets.mouse_demo: mouse_demo
  # - dataset@datasets.mouse44: mouse44
  # - dataset@datasets.mouse23: mouse23

  # - dataset@datasets.pupdev: pupdev
  # - dataset@datasets.pupdev_p7: pupdev_p7
  # - dataset@datasets.pupdev_p14: pupdev_p14
  # - dataset@datasets.pupdev_p21: pupdev_p21
  # - dataset@datasets.pupdev_p30: pupdev_p30  

  - model: vae_ci
  - dataloader: default

expdir: /home/tianqingli/dl-projects/vqmap2/experiments/test
expname: test
overwrite: true
automatic_naming: false
seed: 42
use_wandb: false

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 0.0

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 50

train:
  n_epochs: 450
  val_freq: 1
  save_freq: -1
  monitor: val_loss
  latent_vis_freq: -1

  augmentation:
    lr_flip_prob: 0.0
    lr_flip_naive_prob: 0.0
    kpt_dropout_prob: 0.0
    kpt_dropout_max_parts: 3

wandb:
  project: vqmap2
  entity: tianqing-li
  api_key: a27224d1703ddd094b450ba5d62d197b9194335e

hydra:
  run:
    dir: ${expdir}/${expname}
